### ISSUE TITLE
Support Consul K/V store as infra service

### ISSUE THREAD

**Issue by ghost** [mhausenblas/burry.sh#1]
Backing up and restoring the Consul raft db and k/v store would be great.

**Comment by mhausenblas** [comment]
OK @dsh1705 that was an expected one (and thanks for raising it;)

So let's scope this a bit: we're talking about https://www.consul.io/docs/agent/http/kv.html here right?

**Comment by mhausenblas** [comment]
@dsh1705 and @astrostl this feature, Consul K/V store backup and restore is now available

**Comment by astrostl** [comment]
That was fast! Will consider as an alternative to https://github.com/myENA/consul-backinator

**Comment by mhausenblas** [comment]
@astrostl thanks and you're welcome! I wasn't aware of myeENA/consul-backinator but will say that it looks pretty impressive with a couple of features I've been thinking of myself already and even more I didn't.

I'd love to learn from you, based on your experience with myeENA/consul-backinator, what essential stuff is missing in burry and if you run into any issue (sure you will, but will you share them? ;)

Again, thanks for considering to give burry a try.

**Comment by ghost** [comment]
@mhausenblas: Wow... so fast that I did not even think of checking in on this status - very cool!
@astrostl: thanks for the heads up on consul-backinator - I, too, was not aware of this.
I will be testing these solutions in the coming weeks - much to do!
