### ISSUE TITLE
aux.go file is invalid for windows

### ISSUE THREAD

**Issue by FrancoisPoinsot** [mhausenblas/burry.sh#13]
On windows system `aux` is reserved and cannot be used as a file name.
[MSDN](https://msdn.microsoft.com/en-us/library/aa365247(v=vs.85).aspx#file_and_directory_names)

Windows user cannot clone this repository without going through bash for windows

a quick solution would be to just rename aux.go file to anything else

**Comment by mhausenblas** [comment]
Wow, amazing find @FrancoisPoinsot and thanks a lot for pointing this out! I was totally not aware of this 8->
