### ISSUE TITLE
Add v3 data support

### ISSUE THREAD

**Issue by pablokbs** [mhausenblas/burry.sh#21]
Hello, I've been using this tool for a while and it's working great. But I recently upgraded to etcdv3 and seems like the v3 data is not being backed up. 

It would be nice to have support for this

Thanks

**Comment by mhausenblas** [comment]
Thanks for the kind words. Yeah, etcd3 API is not supported and I don't plan to add it here since I don't actively work on the tool anymore. However, for etcd, maybe you want to check out one of my more recent projects called [ReShifter](http://reshifter.info) which comes with etcd3 support.

**Comment by pablokbs** [comment]
Great. I'll check it out thanks!
