### ISSUE TITLE
testing of etcd

### ISSUE THREAD

**Issue by sonijenk** [mhausenblas/burry.sh#29]
Great tool. I have a question about the etcd backup scripts.  Could you please help?

1. What are the pre-req of running etcd backup ?
2. How did you test the backup have restored all the key-values pairs that is stored in etcd?
For example if I delete some of the key value pairs before taking a backup how did you ensure that the keys-values is restored after the etcd restore?

I tried with etctdctl command for V3  to retrieve all the keys-value pairs stored before backup and verify the data integrity after the backup . But I could not find a single command to achieve this? 
https://coreos.com/etcd/docs/latest/dev-guide/interacting_v3.html

**Comment by mhausenblas** [comment]
Please peruse the [background](https://github.com/mhausenblas/burry.sh/blob/master/background.md) since I don't have cycles to provide 1st level support for a project I'm not actively working on anymore.
