### ISSUE TITLE
SSL/TLS support?

### ISSUE THREAD

**Issue by dynek** [mhausenblas/burry.sh#6]
Hello,

Wanted to give burry a try but our ETCd cluster is full HTTPs.

When passing endpoing hostname:2379 burry says:
`ERRO[0000] client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response "\x15\x03\x01\x00\x02\x02"`

If I specifically mention https:// in front I get:
`ERRO[0000] client: etcd cluster is unavailable or misconfigured; error #0: dial tcp: lookup https: no such host
`
Is burry capable of SSL/TLS?

Thank you!

**Comment by mhausenblas** [comment]
Thanks for raising this issue @dynek. No, at the moment there's no support for SSL/TLS, need to be on the network or proxy it. I'll have a look into that as soon as I get a chance.
